/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 jayden-animated.gltf 
*/

import React, { useRef, useEffect, useState } from "react"
import { useGLTF, useAnimations, Html } from "@react-three/drei"
import Scene from "./scene"
import { useFrame } from "react-three-fiber"
import modelPath from "../../models/jayden-animated-6.glb"
// import roomPath from "../../models/just-the-room.glb"

export default function Model({ isLoaded, currentScene }) {
  const [activeScene, setActiveScene] = useState("")
  const group = useRef()

  const { nodes, materials, animations } = useGLTF(modelPath)
  // const model = useGLTF(roomPath)

  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions[currentScene]?.reset().fadeIn(0.5).play()
    setActiveScene(currentScene)

    if (currentScene === "walking") {
      actions["earth rotating"]?.play()
    } else {
      actions["earth rotating"]?.stop()
    }

    return () => {
      actions[currentScene]?.fadeOut(0.5)
    }
  }, [currentScene])

  useEffect(() => {
    setActiveScene(currentScene)
  }, [])

  const planeRef = useRef()
  const [positionY, setPositionY] = useState(0)

  const armatureRef = useRef()
  const [armaturePositionY, setArmaturePositionY] = useState(-3)

  useEffect(() => {
    const animatePositionY = () => {
      if (positionY > -0.5 && activeScene === "walking") {
        setPositionY(prevY => Math.min(prevY - 0.02, 0))
      }
      if (positionY < 0 && activeScene !== "walking") {
        setPositionY(prevY => Math.min(prevY + 0.02, 0))
      }
    }

    animatePositionY()
  }, [positionY, activeScene])

  useEffect(() => {
    const animateArmaturePositionY = () => {
      if (armaturePositionY < 0 && isLoaded) {
        setArmaturePositionY(prevY => Math.min(prevY + 0.0022, 0))
      }
    }

    animateArmaturePositionY()
  }, [armaturePositionY, isLoaded])

  useFrame(() => {
    planeRef.current.position.y = positionY
    armatureRef.current.position.y = armaturePositionY
  })

  return (
    <group ref={group} position={[1, -1.2, 0]} dispose={null}>
      <group name="Scene">
        <group ref={armatureRef} name="Armature">
          {/* <Scene activeScene={activeScene} name="typing">
            <primitive object={model.scene} />
          </Scene> */}

          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
          <primitive object={nodes.Ctrl_Master} />
          <skinnedMesh
            name="Ears"
            geometry={nodes.Ears.geometry}
            material={materials["Skin.001"]}
            skeleton={nodes.Ears.skeleton}
          />
          <skinnedMesh
            name="Eyes"
            geometry={nodes.Eyes.geometry}
            material={materials["Eyes.001"]}
            skeleton={nodes.Eyes.skeleton}
          />
          <skinnedMesh
            name="Glasses"
            geometry={nodes.Glasses.geometry}
            material={materials["Glasses.001"]}
            skeleton={nodes.Glasses.skeleton}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials["Hair.001"]}
            skeleton={nodes.Hair.skeleton}
          />
          <skinnedMesh
            name="Hands"
            geometry={nodes.Hands.geometry}
            material={materials["Skin.001"]}
            skeleton={nodes.Hands.skeleton}
          />
          <skinnedMesh
            name="Head"
            geometry={nodes.Head.geometry}
            material={materials["Skin.001"]}
            skeleton={nodes.Head.skeleton}
          />
          <skinnedMesh
            name="Logo"
            geometry={nodes.Logo.geometry}
            material={materials["Sweater Logo.001"]}
            skeleton={nodes.Logo.skeleton}
          />
          <skinnedMesh
            name="Pants"
            geometry={nodes.Pants.geometry}
            material={materials["Material.002"]}
            skeleton={nodes.Pants.skeleton}
          />
          <skinnedMesh
            name="Shoelaces"
            geometry={nodes.Shoelaces.geometry}
            material={materials["Laces.001"]}
            skeleton={nodes.Shoelaces.skeleton}
          />
          <skinnedMesh
            name="Shoes"
            geometry={nodes.Shoes.geometry}
            material={materials["Shoe Body.001"]}
            skeleton={nodes.Shoes.skeleton}
          />
          <skinnedMesh
            name="Sweater"
            geometry={nodes.Sweater.geometry}
            material={materials["Sweater.001"]}
            skeleton={nodes.Sweater.skeleton}
          />
        </group>
        <Scene activeScene={activeScene} name="playing piano">
          <group
            name="Playing_Piano"
            position={[0.048, 1.104, 1.692]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[1, 1.072, 1]}
          >
            <mesh
              name="Cube167"
              geometry={nodes.Cube167.geometry}
              material={materials["Black.001"]}
            />
            <mesh
              name="Cube167_1"
              geometry={nodes.Cube167_1.geometry}
              material={materials["Gold.001"]}
            />
            <mesh
              name="Cube167_2"
              geometry={nodes.Cube167_2.geometry}
              material={materials["Wood.001"]}
            />
            <mesh
              name="Cube167_3"
              geometry={nodes.Cube167_3.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube167_4"
              geometry={nodes.Cube167_4.geometry}
              material={materials["Material.006"]}
            />
          </group>
        </Scene>
        <Scene activeScene={activeScene} name="walking">
          <group name="Earth" position={[0, -3.536, 0]} scale={3.623}>
            <mesh
              name="Cube001_Cube004"
              geometry={nodes.Cube001_Cube004.geometry}
              material={materials["Red.001"]}
            />
            <mesh
              name="Cube001_Cube004_1"
              geometry={nodes.Cube001_Cube004_1.geometry}
              material={materials["White.001"]}
            />
            <mesh
              name="Cube001_Cube004_2"
              geometry={nodes.Cube001_Cube004_2.geometry}
              material={materials["LightBrown.001"]}
            />
            <mesh
              name="Cube001_Cube004_3"
              geometry={nodes.Cube001_Cube004_3.geometry}
              material={materials["Blue.001"]}
            />
            <mesh
              name="Cube001_Cube004_4"
              geometry={nodes.Cube001_Cube004_4.geometry}
              material={materials["Green.001"]}
            />
            <mesh
              name="Cube001_Cube004_5"
              geometry={nodes.Cube001_Cube004_5.geometry}
              material={materials["Snow.001"]}
            />
            <mesh
              name="Cube001_Cube004_6"
              geometry={nodes.Cube001_Cube004_6.geometry}
              material={materials["Brown.001"]}
            />
            <mesh
              name="Cube001_Cube004_7"
              geometry={nodes.Cube001_Cube004_7.geometry}
              material={materials["DarkGreen.001"]}
            />
          </group>
        </Scene>
        <Scene activeScene={activeScene} name="typing">
          <mesh
            name="Typing001"
            geometry={nodes.Typing001.geometry}
            material={materials.imac}
            position={[-0.043, 0.564, 0.842]}
            rotation={[Math.PI, -0.022, Math.PI]}
            scale={[0.717, 0.162, 0.198]}
          />
          <mesh
            name="Typing002"
            geometry={nodes.Typing002.geometry}
            material={materials.imac}
            position={[-1.16, 0.564, 0.982]}
            rotation={[Math.PI, -0.41, Math.PI]}
            scale={[0.433, 0.162, 0.162]}
          />
          <mesh
            name="Typing003"
            geometry={nodes.Typing003.geometry}
            material={materials["imac.001"]}
            position={[-0.264, 1.519, 2.01]}
            rotation={[1.694, 0, 0.001]}
            scale={[-1.121, -1.123, -0.835]}
          >
            <mesh
              name="Typing004"
              geometry={nodes.Typing004.geometry}
              material={materials["imac.001"]}
              position={[-0.219, -0.012, -1.018]}
              rotation={[-0.132, -0.049, -1.569]}
              scale={[-0.082, -0.119, -0.109]}
            />
          </mesh>
          <mesh
            name="Typing005"
            geometry={nodes.Typing005.geometry}
            material={materials.white}
            position={[-0.375, 0.287, 1.501]}
            rotation={[0, -1.571, 0]}
            scale={[0.814, 1.054, 1.068]}
          >
            <mesh
              name="Typing006"
              geometry={nodes.Typing006.geometry}
              material={materials.decor}
              position={[0.47, -0.284, 0.649]}
              scale={[0.217, 0.061, 0.129]}
            />
            <mesh
              name="Typing007"
              geometry={nodes.Typing007.geometry}
              material={materials.decor}
              position={[-0.743, -0.284, 0.649]}
              scale={[0.217, 0.061, 0.129]}
            />
            <mesh
              name="Typing008"
              geometry={nodes.Typing008.geometry}
              material={materials.decor}
              position={[0.47, -0.284, -1.083]}
              scale={[0.217, 0.061, 0.129]}
            />
            <mesh
              name="Typing009"
              geometry={nodes.Typing009.geometry}
              material={materials.decor}
              position={[-0.743, -0.284, -1.083]}
              scale={[0.217, 0.061, 0.129]}
            />
          </mesh>
          <mesh
            name="Typing011"
            geometry={nodes.Typing011.geometry}
            material={materials["white.003"]}
            position={[0.918, 0.83, 1.718]}
            rotation={[-Math.PI, 0.191, -Math.PI]}
            scale={[-0.13, -0.153, -0.13]}
          >
            <group name="Typing010" position={[0, 0.515, 0]} scale={1.051}>
              <mesh
                name="Cylinder032"
                geometry={nodes.Cylinder032.geometry}
                material={materials["imac.002"]}
              />
              <mesh
                name="Cylinder032_1"
                geometry={nodes.Cylinder032_1.geometry}
                material={materials["decor.002"]}
              />
            </group>
          </mesh>
        </Scene>
        <Scene activeScene={activeScene} name="thinking">
          <mesh
            name="Talking023"
            geometry={nodes.Talking023.geometry}
            material={materials["white.001"]}
            position={[0.118, 1.117, 1.594]}
            rotation={[-1.45, -0.018, 2.971]}
            scale={[-0.426, -0.358, -0.358]}
          />
          <mesh
            name="Talking010"
            geometry={nodes.Talking010.geometry}
            material={materials["floor lamp head.001"]}
            position={[-0.214, 1.388, 1.558]}
            rotation={[-1.414, -0.032, 2.945]}
            scale={-0.085}
          />
          <mesh
            name="Talking009"
            geometry={nodes.Talking009.geometry}
            material={materials["carpet.002"]}
            position={[-0.107, 1.388, 1.58]}
            rotation={[-1.414, -0.032, 2.945]}
            scale={-0.085}
          />
          <mesh
            name="Talking008"
            geometry={nodes.Talking008.geometry}
            material={materials["plant.003"]}
            position={[0, 1.388, 1.601]}
            rotation={[-1.414, -0.032, 2.945]}
            scale={-0.085}
          />
          <mesh
            name="Talking022"
            geometry={nodes.Talking022.geometry}
            material={materials["carpet.003"]}
            position={[0.139, 1.21, 1.538]}
            rotation={[-1.442, -0.026, 2.944]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking021"
            geometry={nodes.Talking021.geometry}
            material={materials["carpet.003"]}
            position={[0.144, 1.041, 1.515]}
            rotation={[-1.442, -0.026, 2.944]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking020"
            geometry={nodes.Talking020.geometry}
            material={materials["carpet.003"]}
            position={[-0.215, 1.041, 1.447]}
            rotation={[-1.442, -0.026, 2.944]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking019"
            geometry={nodes.Talking019.geometry}
            material={materials["carpet.003"]}
            position={[-1.629, 1.996, 1.432]}
            rotation={[-1.552, -0.004, 2.942]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking018"
            geometry={nodes.Talking018.geometry}
            material={materials["carpet.003"]}
            position={[-1.629, 2.169, 1.431]}
            rotation={[-1.552, -0.004, 2.942]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking017"
            geometry={nodes.Talking017.geometry}
            material={materials["carpet.003"]}
            position={[-1.254, 2.169, 1.507]}
            rotation={[-1.552, -0.004, 2.942]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking016"
            geometry={nodes.Talking016.geometry}
            material={materials["white.001"]}
            position={[-1.629, 1.439, 1.434]}
            rotation={[-1.575, 0.001, 2.942]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking015"
            geometry={nodes.Talking015.geometry}
            material={materials["white.001"]}
            position={[-1.629, 1.267, 1.432]}
            rotation={[-1.575, 0.001, 2.942]}
            scale={[0.318, 0.166, 0.042]}
          />
          <mesh
            name="Talking014"
            geometry={nodes.Talking014.geometry}
            material={materials["plant.001"]}
            position={[-0.067, 2.316, 1.612]}
            rotation={[-1.56, 0.004, 2.969]}
            scale={[-0.426, -0.358, -0.358]}
          />
          <mesh
            name="Talking007"
            geometry={nodes.Talking007.geometry}
            material={materials["floor lamp head.001"]}
            position={[-0.393, 2.589, 1.546]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking005"
            geometry={nodes.Talking005.geometry}
            material={materials["carpet.002"]}
            position={[-0.286, 2.589, 1.568]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking004"
            geometry={nodes.Talking004.geometry}
            material={materials["plant.003"]}
            position={[-0.178, 2.589, 1.59]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking013"
            geometry={nodes.Talking013.geometry}
            material={materials["Material.003"]}
            position={[-0.285, 2.429, 1.907]}
            rotation={[-1.56, 0.004, 2.969]}
            scale={[-0.426, -0.358, -0.358]}
          />
          <mesh
            name="Talking003"
            geometry={nodes.Talking003.geometry}
            material={materials["floor lamp head.001"]}
            position={[-0.612, 2.702, 1.84]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking002"
            geometry={nodes.Talking002.geometry}
            material={materials["carpet.002"]}
            position={[-0.505, 2.702, 1.862]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking001"
            geometry={nodes.Talking001.geometry}
            material={materials["plant.003"]}
            position={[-0.397, 2.702, 1.884]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking011"
            geometry={nodes.Talking011.geometry}
            material={materials["carpet.003"]}
            position={[-1.731, 1.38, 1.593]}
            rotation={[0, 1.371, Math.PI / 2]}
            scale={[-0.3, -0.479, -0.326]}
          />
          <mesh
            name="Talking012"
            geometry={nodes.Talking012.geometry}
            material={materials["white.001"]}
            position={[-1.731, 2.131, 1.593]}
            rotation={[0, 1.371, Math.PI / 2]}
            scale={[-0.3, -0.479, -0.326]}
          />
          <mesh
            name="Talking006"
            geometry={nodes.Talking006.geometry}
            material={materials["floor lamp head.002"]}
            position={[-0.393, 2.589, 1.546]}
            rotation={[-1.524, -0.009, 2.942]}
            scale={-0.085}
          />
          <mesh
            name="Talking024"
            geometry={nodes.Talking024.geometry}
            material={materials["white.004"]}
            position={[-0.791, 2.115, 1.852]}
            rotation={[0, -0.199, 0]}
            scale={[-0.034, -1.031, -0.034]}
          />
        </Scene>

        <mesh ref={planeRef} rotation-x={-Math.PI * 0.5} scale={10}>
          <planeGeometry />
          <meshBasicMaterial toneMapped={false} color="white" />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload(modelPath)
