/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 jayden-animated-4.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/jayden-animated-4.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="cs_grp">
          <group name="cs_arm_fk" position={[1.5, 8.5, 0]} scale={0.822} />
          <group name="cs_calf_fk" position={[0.5, 8.5, 0]} scale={0.822} />
          <group name="cs_circle" position={[0.5, 4.5, 0]} scale={0.206} />
          <group name="cs_foot" position={[0.5, 10.5, 0]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
          <group name="cs_foot001" position={[0.5, 10.5, 0]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
          <group name="cs_foot002" position={[0.5, 10.5, 0]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
          <group name="cs_foot_01" position={[0.5, 18.5, 0]} rotation={[0, Math.PI / 2, 0]} scale={2.186} />
          <group name="cs_foot_roll" position={[0.5, 12.5, 0]} scale={0.592} />
          <group name="cs_forearm_fk" position={[2.5, 8.5, 0]} scale={0.822} />
          <group name="cs_hand" position={[0.5, 19.5, 0]} rotation={[-Math.PI, 0, 0]} scale={0.308} />
          <group name="cs_head" position={[0.5, 13.5, 0]} scale={0.206} />
          <group name="cs_hips" position={[0.5, 11.5, 0]} scale={0.206} />
          <group name="cs_master" position={[0.5, 17.5, 0]} scale={0.1} />
          <group name="cs_neck" position={[0.5, 14.5, 0]} scale={0.206} />
          <group name="cs_shoulder_left" position={[0.5, 15.5, 0]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={1.038} />
          <group name="cs_shoulder_right" position={[0.5, 16.5, 0]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={1.038} />
          <group name="cs_sphere" position={[0.5, 2.5, 0]} scale={0.206} />
          <group name="cs_sphere_012" position={[3.5, 2.5, 0]} scale={0.206} />
          <group name="cs_square" position={[1.5, 1.497, 0]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
          <group name="cs_square_2" position={[0.5, 1.497, 0]} rotation={[-Math.PI, 0, 0]} scale={0.154} />
          <group name="cs_thigh_fk" position={[0.5, 7.5, 0]} scale={0.822} />
          <group name="cs_toe" position={[0.5, 9.5, 0]} scale={0.429} />
        </group>
        <group name="Waving" position={[-6.744, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <group name="Talking" position={[-5.375, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_1} />
        </group>
        <group name="Typing" position={[-3.635, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips_2} />
        </group>
        <group name="Armature">
          <primitive object={nodes.mixamorigHips_3} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
          <skinnedMesh name="Ears" geometry={nodes.Ears.geometry} material={materials['Skin.001']} skeleton={nodes.Ears.skeleton} />
          <skinnedMesh name="Eyes" geometry={nodes.Eyes.geometry} material={materials['Eyes.001']} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh name="Glasses" geometry={nodes.Glasses.geometry} material={materials['Glasses.001']} skeleton={nodes.Glasses.skeleton} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials['Hair.001']} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="Hands" geometry={nodes.Hands.geometry} material={materials['Skin.001']} skeleton={nodes.Hands.skeleton} />
          <skinnedMesh name="Head" geometry={nodes.Head.geometry} material={materials['Skin.001']} skeleton={nodes.Head.skeleton} />
          <skinnedMesh name="Pants" geometry={nodes.Pants.geometry} material={materials['Material.002']} skeleton={nodes.Pants.skeleton} />
          <skinnedMesh name="Shoelaces" geometry={nodes.Shoelaces.geometry} material={materials['Laces.001']} skeleton={nodes.Shoelaces.skeleton} />
          <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={materials['Shoe Body.001']} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh name="Sweater" geometry={nodes.Sweater.geometry} material={materials['Sweater.001']} skeleton={nodes.Sweater.skeleton} />
          <skinnedMesh name="Sweater001" geometry={nodes.Sweater001.geometry} material={materials['Sweater Logo.001']} skeleton={nodes.Sweater001.skeleton} />
        </group>
        <mesh name="Body" geometry={nodes.Body.geometry} material={materials.Sweater} position={[0, 1.321, 0]} scale={0.427} />
      </group>
    </group>
  )
}

useGLTF.preload('/jayden-animated-4.gltf')
